# Generated by Django 2.2 on 2021-02-07 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDiscogs', models.PositiveIntegerField(verbose_name='DiscogsID артиста')),
                ('name', models.CharField(max_length=128, verbose_name="Artist's name")),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name="Label's name")),
                ('idDiscogs', models.PositiveIntegerField(verbose_name='DiscogsID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name="Tag's name")),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idYandex', models.PositiveIntegerField(verbose_name='YandexMusicID')),
                ('idDiscogs', models.PositiveIntegerField(verbose_name='DiscogsID')),
                ('idDiscogsSecondary', models.PositiveIntegerField(verbose_name='DiscogsSecondaryID')),
                ('name', models.CharField(max_length=128, verbose_name="Album's name")),
                ('image', models.ImageField(blank=True, upload_to='Cover image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Artist')),
                ('labels', models.ManyToManyField(to='mainapp.Label')),
                ('tags', models.ManyToManyField(to='mainapp.Tag')),
            ],
        ),
    ]
