# Generated by Django 2.2 on 2021-02-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210208_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
    ]
