# Generated by Django 2.2 on 2021-02-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210208_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Label'),
        ),
    ]
