# Generated by Django 2.2 on 2021-02-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.Tag'),
        ),
    ]
