# Generated by Django 2.2 on 2021-02-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_album_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='labels',
        ),
        migrations.AddField(
            model_name='album',
            name='labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Label', verbose_name='Labels'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Tag', verbose_name='Tags'),
        ),
    ]
