# Generated by Django 2.2 on 2021-02-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210221_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genred_albums', to='mainapp.Genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labeled_albums', to='mainapp.Label'),
        ),
        migrations.AlterField(
            model_name='album',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='styled_albums', to='mainapp.Style'),
        ),
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_albums', to='mainapp.Tag'),
        ),
    ]
