# Generated by Django 2.2 on 2021-02-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210221_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.PositiveIntegerField(default=0, verbose_name='year'),
        ),
    ]
