# Generated by Django 2.2 on 2021-03-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_album_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(null=True, related_name='albums', to='mainapp.Artist', verbose_name='Artists'),
        ),
    ]
