# Generated by Django 2.2 on 2021-03-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210305_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='idDiscogsSecondary',
            field=models.PositiveIntegerField(null=True, verbose_name='DiscogsSecondaryID'),
        ),
    ]
