# Generated by Django 2.2 on 2021-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20210305_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.AddField(
            model_name='album',
            name='imageURL',
            field=models.CharField(default='', max_length=512, null=True, verbose_name='Image url'),
        ),
    ]
