# Generated by Django 2.2 on 2021-02-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
