# Generated by Django 2.2 on 2021-02-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_album_labels'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='user_albums', to='mainapp.Album'),
        ),
    ]
