# Generated by Django 2.2 on 2021-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_siteuser_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='album_users', to='mainapp.Album', verbose_name='albums'),
        ),
    ]
