# Generated by Django 2.2 on 2021-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210221_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='age'),
        ),
    ]
