# Generated by Django 2.2 on 2021-02-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_siteuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
