# Generated by Django 2.2 on 2021-02-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210223_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='age'),
        ),
    ]
